export const TYPES = {
    AreaConfig: Symbol.for("AreaConfig"),
    Area: Symbol.for("Area"),
    Ball: Symbol.for("Ball"),
    BallNewable: Symbol.for("BallNewable"),
    BallBuilder: Symbol.for("BallBuilder"),
    Tower: Symbol.for("Tower"),
    TowerNewable: Symbol.for("TowerNewable"),
    TowerBuilder: Symbol.for("TowerBuilder"),
    TowerConfig: Symbol.for("TowerConfig"),
    BallOneConfig: Symbol.for("BallOneConfig"),
    BallTwoConfig: Symbol.for("BallTwoConfig"),
    CannonNewable: Symbol.for("CannonNewable"),
    CannonOneConfig: Symbol.for("CannonOneConfig"),
    CannonTwoConfig: Symbol.for("CannonTwoConfig"),
    Cannon: Symbol.for("Cannon"),
    CannonBuilder: Symbol.for("CannonBuilder"),
    RenderEngine: Symbol.for("RenderEngine"),
    GlobalStateManager: Symbol.for("GlobalStateManager"),
    PlayerStateManager: Symbol.for("PlayerStateManager"),
    PlayerStateNewable: Symbol.for("PlayerStateNewable"),
    PlayerState:  Symbol.for("PlayerState"),
}